### ISSUE TITLE
To improve document

### ISSUE THREAD

**Issue by xinetzone** [Nuitka/Nuitka-website#35]
[Watchdog](https://pythonhosted.org/watchdog/): Python API library and shell utilities to monitor file system events.

**Comment by xinetzone** [comment]
To add a subdomain, see [custom-domain-support](https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support).

**Comment by xinetzone** [comment]
Do not use `invoke doc.update` to prevent damage to `locals/` content.

**Comment by kayhayen** [comment]
What I am missing is this: https://pythonrepo.com/repo/executablebooks-sphinx-autobuild-python-documentation

I don't really want to implement anything myself. It seems however, that it's not easily possible to specify a custom build command for this one, so it won't play along with multiple steps to create the site.

**Comment by xinetzone** [comment]
There's another idea for the Sphinx theme.

![](https://user-images.githubusercontent.com/30319120/153745946-24935197-ee46-4cd2-a64c-bdc29cbb6396.png)

**Comment by xinetzone** [comment]
![](https://user-images.githubusercontent.com/30319120/153746013-9f9b631d-dd81-434d-a4e9-a3347e623d76.png)

[sphinxawesome]https://sphinxawesome.xyz/how-to/options/): Supports custom navigation bar.

**Comment by xinetzone** [comment]
**two `locales/`**, I already cleaned it up.

**Comment by xinetzone** [comment]
It might be more convenient to create a new page `switcher.rst`. see brach `switcger`.

**Comment by kayhayen** [comment]
ok, you have disabled parts the workflow though, and post processing also, so currently `main` has breaking changes, does it? Maybe we don't use `main` for development and instead only `translation` as a target, for me it's strange that I would have two branches of very different status. Are you ok, with moving back using that branch, also also have gh-pages fed from there?

**Comment by kayhayen** [comment]
If you don't mind, what I would do now, is to branch `main` as `translation`, and force push the currently accepted, i.e. merged state of the website in its place. Then we click merge, when `translation` looks good on Github pages and start new changes there, that way I can have a stable website. As you can imagine, I don't want to be stressed out by the website breaking down.

**Comment by kayhayen** [comment]
Done, I am going to work on the post-processing, such that there can be hope for it, to look correct on Github pages, since it will make absolute relative paths be relative to the page.

**Comment by xinetzone** [comment]
In the future, maintain both branches simultaneously. If `translation` is ok, merge back to `main`; If there is a problem with `translation`, then pull from `main` to `translation`.

**Comment by kayhayen** [comment]
Exactly, translation should be merged frequently. I basically will setup something that makes a competent diff of the result, such that I can decide if it's only improvements. But generally, I want you to look at gh-pages and have it good.

Right now I deployed the state from yesterday like this: https://nuitka.net/zh_CN/

**Comment by kayhayen** [comment]
I will be working directly on main (after working on a branch privately) to get the post processing to make gh-pages look acceptable, right now I think all CSS, image links, etc. must be broken, whereas download page has images correctly right now.

**Comment by kayhayen** [comment]
Not sure if you understand the problem, but  `/_static` is used by Sphinx in the generated HTML content. But we didn't tell it during generation about the target URL, so this is wrong. Also in a few places, and generally, I would like to be able to just use absolute rather than relative URLs, in the source. The post processing can just update URLs easily. It already visits all images, and links anyway. This is naturally another potentially breaking change. 

The alternative is probably to tell Sphinx about the different target URL. More though needs to be put into this, but on the other hand, I see it as important that `translation` is attempted to be rendered nicely as soon as possible.

For developing and testing breaking changes, so far I have a `staging` website that I use, https://staging.nuitka.net/ where I prepare changes like e.g. currently: https://staging.nuitka.net/posts/python-compile-windows.html until I deem them ready, and I guess, I could automatically make that job that builds it compare stuff with current main.

**Comment by kayhayen** [comment]
Esp. I do not think, you have to do anything about the images by moving them in the repo right now.

**Comment by xinetzone** [comment]
A new solution: using the [pydata-sphinx-theme theme](https://github.com/pydata/pydata-sphinx-theme) theme + Read The Docs.

Case: [xyzstyle](https://xyzstyle.readthedocs.io/zh/latest).

**Comment by xinetzone** [comment]
conf.py

```python
# ``pydata-sphinx-theme`` 配置
# Define the json_url for our version switcher.
json_url = 'https://nuitka.net/_static/switcher.json'

version = 'zh_CN'

switcher_version = version
if "dev" in version:
    switcher_version = "dev"
elif "rc" in version:
    switcher_version = version.split("rc")[0] + " (rc)"


html_theme_options = {
    "switcher": {
        "json_url": json_url,
        "version_match": switcher_version,
        "url_template": "https://pandas.pydata.org/{version}/",
    }
}
```

**Comment by xinetzone** [comment]
`https://nuitka.net/_static/switcher.json`
```json
[
    {
        "name": "zh_CN",
        "version": "latest",
        "url": "https://nuitka.net/zh_CN/latest"
    },
    {
        "name": "main",
        "version": "main",
        "url": "https://nuitka.net/main"
    }
]
```

**Comment by xinetzone** [comment]
Read The Docs:

`readthedocs.yml`:

```yaml
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# Build PDF & ePub * HTML
formats:
  - htmlzip
  - epub
  # - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true
```

more details in [readthedocs config-file/v2](https://docs.readthedocs.io/en/stable/config-file/v2.html).
